Adjusts staging config to publish to different APP ID

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,6 +11,7 @@ jobs:
 
     environment:
       - APP_ID: efaekpejcfjpejdjhkolhlnpepimjcio
+      - DEV_APP_ID: dedacmldgkhekcocalpdeldpmejppjkc
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
       # documented at https://circleci.com/docs/2.0/circleci-images/
@@ -58,7 +59,8 @@ jobs:
       - run:
           name: 'Upload & Publish Extension to the Google Chrome Store'
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "staging" ]; then
+            # If branch is master then publish the app to the Chrome Web Store
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               echo "Uploading..."
               ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
               UPLOAD_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T get-the-gist.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
@@ -72,9 +74,6 @@ jobs:
                 exit 1
               fi
               echo "Upload successful"
-            fi
-            # If branch is master then publish the app to the Chrome Web Store
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               echo "Publishing..."
               PUBLISH_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish")
               echo "$PUBLISH_RESPONSE"
@@ -88,8 +87,21 @@ jobs:
             fi
             # If branch is staging then publish the app for testers only
             if [ "${CIRCLE_BRANCH}" == "staging" ]; then
+              echo "Uploading..."
+              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
+              UPLOAD_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T get-the-gist.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${DEV_APP_ID}")
+              echo "$UPLOAD_RESPONSE"
+              UPLOAD_STATE=$(echo "$UPLOAD_RESPONSE" | jq -r .uploadState)
+              UPLOAD_ERRORS=$(echo "$UPLOAD_RESPONSE" | jq -r .itemError[]?)
+              echo "$UPLOAD_ERRORS"
+              if [ "${UPLOAD_STATE}" == "FAILURE" ]; then
+                echo "ERROR. Unable to upload. [Chrome Extension upload state: ${UPLOAD_STATE}]"
+                echo "$UPLOAD_RESPONSE"
+                exit 1
+              fi
+              echo "Upload successful"
               echo "Publishing to staging..."
-              PUBLISH_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -d "{"publishTarget": "trustedTesters"}" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish")
+              PUBLISH_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -d "{"target": "trustedTesters"}" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${DEV_APP_ID}/publish")
               echo "$PUBLISH_RESPONSE"
               PUBLISH_STATE=$(echo "$PUBLISH_RESPONSE" | jq -r .status[]?)
               if [ "${PUBLISH_STATE}" != "OK" ]; then
